{% set version = "8.0.0" %}

package:
  name: pytest
  version: {{ version }}

source:
  url: https://github.com/pytest-dev/pytest/archive/refs/tags/{{ version }}.tar.gz
  sha256: 53cb6cfe76acd84a8f8279556748bb72e8c4a1be316aa50f5bfb900257aa004b

build:
  number: 0
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytest = pytest:console_main
    - py.test = pytest:console_main

requirements:
  host:
    - pip
    - python
    - setuptools >=42.0
    - setuptools_scm >=6.0
  run:
    - python
    - iniconfig
    - packaging
    - pluggy <2.0,>=1.4.0
    - tomli >=1.0.0
    # colorama is needed only for windows, but okay to have for unix
    # For eg: tqdm does the same thing
    - colorama
    # exceptiongroup should be only [py<311] but let's see if we can keep this noarch.
    - exceptiongroup >=1.0.0rc8
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2

test:
  source_files:
    - testing/
  commands:
    - pytest -h
    - pytest
  imports:
    - pytest

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
